# Generated by Django 5.1.15 on 2026-09-10 17:40

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method'),
        ('payments', '0003_payment_bank_tran_id_payment_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=payments.models.generate_transaction_id, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='val_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['val_id'], name='payments_pa_val_id_bc3153_idx'),
        ),
    ]
