# Generated by Django 6.1 on 2026-08-27 16:56

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_ticket_numbers(apps, schema_editor):
    ContactMessage = apps.get_model('core', 'ContactMessage')
    for contact in ContactMessage.objects.all():
        contact.ticket_number = f"NIT-TKT-{uuid.uuid4().hex[:8].upper()}"
        contact.save(update_fields=['ticket_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Support Ticket / Inquiry', 'verbose_name_plural': 'Support Tickets & Inquiries'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Internal or dispatched reply from support team', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(populate_ticket_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contactmessage',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]

