# Generated by Django 5.1.15 on 2026-09-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_shipping_fee_alter_order_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('tracking_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('raw_last_webhook', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Courier Shipment',
                'verbose_name_plural': 'Courier Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
