# Generated by Django 5.1.15 on 2026-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipping_fee_alter_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery (COD)'), ('SSLCOMMERZ', 'Online Payment (SSLCommerz)')], default='COD', max_length=20),
        ),
    ]
