# Generated by Django 6.1 on 2026-08-25 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Inline SVG or icon representation')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unleash Peak Performance with N-IT Home', max_length=200)),
                ('title_highlight', models.CharField(blank=True, default='N-IT Home', help_text='Part of the title to highlight', max_length=100)),
                ('badge_1', models.CharField(default='Next-Gen Components', max_length=80)),
                ('badge_2', models.CharField(default='In Stock & Ready to Ship', max_length=80)),
                ('lead_text', models.TextField(default='Explore authentic high-performance desktop hardware — flagship NVIDIA & AMD graphics cards, AMD Ryzen 3D V-Cache processors, PCIe Gen5 NVMe storage, and low-latency DDR5 memory kits.')),
                ('perk_1', models.CharField(default='Official Warranty', max_length=80)),
                ('perk_2', models.CharField(default='Same-Day Processing', max_length=80)),
                ('perk_3', models.CharField(default='bKash / Nagad / COD', max_length=80)),
                ('card_tag', models.CharField(default='TOP SELLING FLAGSHIP', max_length=80)),
                ('card_title', models.CharField(default='GeForce RTX 4090 24GB', max_length=120)),
                ('card_price', models.DecimalField(decimal_places=2, default=1699.99, max_digits=10)),
                ('card_link', models.CharField(default='/product/nvidia-geforce-rtx-4090-24gb-founders-edition/', help_text='URL or relative link for the promo button', max_length=255)),
                ('card_button_text', models.CharField(default='View Flagship Hardware →', max_length=80)),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this banner on the homepage. Uncheck to hide it.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Ordering priority (0 is highest priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion Banner',
                'verbose_name_plural': 'Promotion Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_qty', models.PositiveIntegerField(default=10)),
                ('short_description', models.TextField(help_text='Short teaser shown in listing cards', max_length=500)),
                ('long_description', models.TextField(help_text='Detailed markdown/HTML rich description with performance specs')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='CDN or web fallback image', max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Direct MP4 video stream URL', max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('warranty', models.CharField(default='3 Years Manufacturer Warranty', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/4k/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_4k', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Reviewer name', max_length=100)),
                ('author_email', models.EmailField(blank=True, help_text='Reviewer contact email', max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 Stars - Excellent'), (4, '4 Stars - Very Good'), (3, '3 Stars - Average / Good'), (2, '2 Stars - Fair'), (1, '1 Star - Poor')], default=5)),
                ('title', models.CharField(help_text='Review summary or title', max_length=150)),
                ('comment', models.TextField(help_text='Detailed feedback, benchmark results, or comments')),
                ('is_verified_purchase', models.BooleanField(default=True, help_text='Verified hardware buyer badge')),
                ('is_approved', models.BooleanField(default=True, help_text='Check to display on public product page; uncheck to hide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews & Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Key Specifications', max_length=60)),
                ('spec_name', models.CharField(max_length=100)),
                ('spec_value', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
