# Generated by Django 5.1.15 on 2026-08-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Inline SVG or icon representation')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_qty', models.PositiveIntegerField(default=10)),
                ('short_description', models.TextField(help_text='Short teaser shown in listing cards', max_length=500)),
                ('long_description', models.TextField(help_text='Detailed markdown/HTML rich description with performance specs')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='CDN or web fallback image', max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Direct MP4 video stream URL', max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('warranty', models.CharField(default='3 Years Manufacturer Warranty', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/4k/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_4k', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Key Specifications', max_length=60)),
                ('spec_name', models.CharField(max_length=100)),
                ('spec_value', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
