# Generated by Django 6.1 on 2026-08-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu_cores',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CPU physical core count (e.g. 4, 6, 8, 12, 16, 24)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_series',
            field=models.CharField(blank=True, choices=[('i3', 'Intel Core i3'), ('i5', 'Intel Core i5'), ('i7', 'Intel Core i7'), ('i9', 'Intel Core i9'), ('ryzen3', 'AMD Ryzen 3'), ('ryzen5', 'AMD Ryzen 5'), ('ryzen7', 'AMD Ryzen 7'), ('ryzen9', 'AMD Ryzen 9'), ('snapdragon', 'Qualcomm Snapdragon'), ('other', 'Other / Workstation')], help_text='CPU series e.g. Intel Core i3/i5/i7/i9 or AMD Ryzen 3/5/7/9', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_threads',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CPU thread count (e.g. 8, 12, 16, 24, 32)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='generation',
            field=models.CharField(blank=True, choices=[('gen3', 'Gen 3 (PCIe 3.0 / DDR3)'), ('gen4', 'Gen 4 (PCIe 4.0 / DDR4)'), ('gen5', 'Gen 5 (PCIe 5.0 / DDR5)')], help_text='Hardware generation e.g. Gen3, Gen4, Gen5', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_vram',
            field=models.CharField(blank=True, choices=[('8gb', '8GB'), ('12gb', '12GB'), ('16gb', '16GB'), ('24gb', '24GB'), ('32gb', '32GB'), ('64gb', '64GB'), ('96gb', '96GB')], help_text='GPU dedicated VRAM e.g. 8GB, 12GB, 16GB, 24GB, 32GB, 64GB, 96GB', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_capacity',
            field=models.CharField(blank=True, choices=[('8gb', '8GB'), ('16gb', '16GB'), ('32gb', '32GB'), ('64gb', '64GB'), ('128gb', '128GB')], help_text='RAM capacity e.g. 8GB, 16GB, 32GB, 64GB', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd_capacity',
            field=models.CharField(blank=True, choices=[('512gb', '512GB'), ('1tb', '1TB'), ('2tb', '2TB'), ('4tb', '4TB'), ('8tb', '8TB')], help_text='SSD storage capacity e.g. 512GB, 1TB, 2TB, 4TB', max_length=20, null=True),
        ),
    ]
