# Generated by Django 6.1 on 2026-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cpu_cores_product_cpu_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='promotionbanner',
            name='card_price',
            field=models.DecimalField(decimal_places=2, default=203999.0, max_digits=12),
        ),
    ]
