# Generated by Django 6.1 on 2026-08-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_original_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcie_version',
            field=models.CharField(blank=True, choices=[('pcie3', 'PCIe 3.0'), ('pcie4', 'PCIe 4.0'), ('pcie5', 'PCIe 5.0')], help_text='PCIe interface e.g. PCIe 3.0, PCIe 4.0, PCIe 5.0', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_type',
            field=models.CharField(blank=True, choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], help_text='RAM standard e.g. DDR3, DDR4, DDR5', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='generation',
            field=models.CharField(blank=True, choices=[('gen3', 'Gen 3'), ('gen4', 'Gen 4'), ('gen5', 'Gen 5')], help_text='SSD generation e.g. Gen 3, Gen 4, Gen 5', max_length=20, null=True),
        ),
    ]
